name: Package Application with Pyinstaller

on:
  push:
    branches: [ pyinstaller-with-github-actions ]
  pull_request:
    branches: [ pyinstaller-with-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Changing DEV version to current tag
      run: sed -i "s/\"DEV\"/\"2025.05.29\"/g" "src/MyAnimeManager3/src/core.py"

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        requirements: requirements.txt
        spec: .pyinstaller.spec

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.ref_name }}-windows
        path: dist/windows

    - name: Create an empty file for the portable artifact
      run: touch dist/windows/.portable

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.ref_name }}-windows-portable
        path: | 
          dist/windows
          .portable
