name: Package application with Pyinstaller

on:
  push:
    branches: [ master, main ]
    tags:        
      - '202*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
    - uses: actions/checkout@v4

    - name: Get latest commit date on branch
      run: |
        # Get the commit date on the current branch
        LATEST_COMMIT_DATE=$(git show -s --format=%cd --date=format:"%Y.%m.%d")
        echo "LATEST_COMMIT_DATE=${LATEST_COMMIT_DATE}" >> $GITHUB_ENV
        echo "Latest commit date: ${LATEST_COMMIT_DATE}"

    - name: Changing DEV version to current tag
      run: sed -i "s/\"DEV\"/\"$LATEST_COMMIT_DATE\"/g" "src/core.py"

    - name: Converting png icon to ico
      run: | 
        sudo apt install imagemagick -y
        convert "src/resources/icon.png" -define icon:auto-resize="256,128,96,64,48,32,16" "src/resources/icon.ico"
     
    - name: Packaging application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        requirements: requirements.txt
        spec: .pyinstaller.spec

    #- uses: actions/upload-artifact@v4
    #  with:
    #    name: ${{ github.event.repository.name }}-${{ env.LATEST_COMMIT_DATE }}-windows.zip
    #    path: dist/windows
    #    compression-level: 9
    #    include-hidden-files: true

    - name: Creating zip before upload release
      run: | 
        cd dist/windows/MyAnimeManager3
        sudo zip -9 -r "../myanimemanager3-${LATEST_COMMIT_DATE}-windows.zip" *

    #- name: Upload artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: ${{ github.event.repository.name }}-${{ env.LATEST_COMMIT_DATE }}-windows-portable.zip
    #    path: dist/windows
    #    compression-level: 9
    #    include-hidden-files: true

    - name: Creating portable zip for before upload to release
      run: |
        cd dist/windows/MyAnimeManager3
        touch _internal/.portable
        sudo zip -9 -r "../myanimemanager3-${LATEST_COMMIT_DATE}-windows-portable.zip" *
    
    - name: Upload file to release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/windows/myanimemanager3-${{ github.ref_name }}-windows.zip
          dist/windows/myanimemanager3-${{ github.ref_name }}-windows-portable.zip
